[mongo_configsvr]
cfg1 ansible_host=10.10.10.11
cfg2 ansible_host=10.10.10.12
cfg3 ansible_host=10.10.10.13

[mongo_shard01]
sh1a ansible_host=10.10.20.11
sh1b ansible_host=10.10.20.12
sh1c ansible_host=10.10.20.13

[mongo_shard02]
sh2a ansible_host=10.10.30.11
sh2b ansible_host=10.10.30.12
sh2c ansible_host=10.10.30.13

[mongo_mongos]
mongos1 ansible_host=10.10.40.11
mongos2 ansible_host=10.10.40.12

[all:vars]
ansible_user=ubuntu
ansible_become=true
